name: MacOS Workflow
on: [workflow_dispatch]

jobs:
  bun_on_macos:
    name: test bun installer on macos
    runs-on: macos-latest

    steps:
      - name: Install bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Test bun
        run: source /Users/runner/.bashrc && bun --version
