name: MacOS Workflow
on: [workflow_dispatch]

jobs:
  bun_on_macos:
    name: test bun installer on macos
    runs-on: macos-15

    steps:
      - name: Install bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Test bun
        run: source /Users/runner/.bashrc && bun --version

      - name: Check OS version
        run: sw_vers

      - name: Check brand
        run: sysctl -n machdep.cpu.brand_string

      - name: Check HV
        run: system_profiler SPHardwareDataType | grep -i "chip"

      - name: Check HV FW
        run: ls /System/Library/Frameworks/Hypervisor.framework

      - name: Install docker
        run: brew install docker && docker run --rm hello-world

