name: KVM Workflow
on:
  workflow_dispatch:

jobs:
  bun_on_ubuntu:
    name: Test bun installer on nested VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout docker darwin repo
        uses: actions/checkout@v4
        with:
          repository: sickcodes/Docker-OSX
          path: docker-darwin

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install qemu utils
        run: sudo apt-get install -y qemu-utils

      - name: Get Darwin images from cache
        id: restore-base-cache
        uses: actions/cache/restore@v4
        with:
          path: BaseSystem.dmg
          key: ${{ runner.os }}-base-system
          # key: ${{ runner.os }}-${{ hashFiles('BaseSystem.dmg') }}
          # restore-keys: |
          #   ${{ runner.os }}-

      - name: Download Darwin images
        if: steps.restore-base-cache.outputs.cache-hit != 'true'
        run: python3 scripts/fetch_darwin.py -s big-sur

      - uses: actions/cache/save@v4
        if: always() && steps.restore-base-cache.outputs.cache-hit != 'true'
        id: save-base-cache
        with:
          path: BaseSystem.dmg
          key: ${{ steps.restore-base-cache.outputs.cache-primary-key }}
          # key: ${{ runner.os }}-${{ hashFiles('BaseSystem.dmg') }}

      - name: Get base img from cache
        id: restore-base-img-cache
        uses: actions/cache/restore@v4
        with:
          path: BaseSystem.img
          key: ${{ runner.os }}-base-img-system

      - name: Convert base dmg to img
        if: steps.restore-base-img-cache.outputs.cache-hit != 'true'
        run: qemu-img convert BaseSystem.dmg -O qcow2 -p -c BaseSystem.img

      - uses: actions/cache/save@v4
        if: always() && steps.restore-base-img-cache.outputs.cache-hit != 'true'
        id: save-base-img-cache
        with:
          path: BaseSystem.img
          key: ${{ steps.restore-base-img-cache.outputs.cache-primary-key }}

      - name: Create HDD
        run: qemu-img create -f qcow2 mac_hdd_ng.img 35G

      - name: Build docker darwin
        run: |
          cd docker-darwin
          docker build --build-arg COMPLETE=  -t docker-osx:auto -f Dockerfile.auto .

      - name: Run docker darwin
        run: |
          docker run \
            -v ${PWD}/mac_hdd_ng.img:/image \
            -v ${PWD}/BaseSystem.img:/home/arch/OSX-KVM/BaseSystem.img \
            -p 50922:10022 \
            -e SHORTNAME=big-sur \
            -e HEADLESS=true \
            -e OSX_COMMANDS='/bin/bash -c "sw_vers"' \
            --device /dev/kvm \
            docker-osx:auto
